// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Cari: typeof import('./src/components/Cari.vue')['default']
    Head: typeof import('@vueuse/head')['Head']
    Island: typeof import('./node_modules/.pnpm/iles@0.7.38/node_modules/iles/dist/client/app/components/Island.vue')['default']
    Komentar: typeof import('./src/components/Komentar.vue')['default']
  }
}

export { }
