// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Cari: typeof import('./src/components/Cari.vue')['default']
    Komentar: typeof import('./src/components/Komentar.vue')['default']
  }
}

export { }
